[문제134] emp.csv 파일의 데이터를 판다스를 이용해서 읽어 들인 후 급여가 10000 이상인 사원들의 이름, 급여, 입사일을 출력해주세요.
```python
import pandas as pd
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
file[file.SALARY >= 10000][['LAST_NAME', 'SALARY', 'HIRE_DATE']]
```
[문제135] 급여 10000 이상인 사원들의 이름과 급여, 입사일를 출력하세요. 급여를 기준으로 내림차순하세요.
```python
import pandas as pd
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
file[file.SALARY >= 10000][['LAST_NAME', 'SALARY', 'HIRE_DATE']].sort_values(by='SALARY', axis=0, ascending=False)
```
[문제136] 급여를 많이 받는 순으로 10위 까지를 구하세요. 
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
# 정렬만 사용
file.sort_values(by='SALARY', ascending=False)[:10]

# rank로 구한 뒤 정렬
file[file.SALARY.rank(ascending=False, method='first') <= 10].sort_values(by='SALARY', ascending=False)
```
```python
# 선생님 답
emp[emp['SALARY'].rank(ascending=False, method='dense')<=10][['EMPLOYEE_ID', 'LAST_NAME', 'SALARY']]

emp['rank'] = emp['SALARY'].rank(ascending=False, method='dense')
emp[emp['rank'] <= 10].sort_values('rank')
```
[문제137] 직업이 AD_VP, AD_PRES 인 사원들의 이름, 급여, 직업을 출력하세요.
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')

file[file.JOB_ID.isin(['AD_VP', 'AD_PRES'])][['LAST_NAME', 'SALARY', 'JOB_ID']]
```

[문제138] 직업이 AD_VP ,AD_PRES 아닌 사원들의 이름, 급여, 직업을 출력하세요.
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')

file[~file.JOB_ID.isin(['AD_VP', 'AD_PRES'])][['LAST_NAME', 'SALARY', 'JOB_ID']]
```

[문제139] 커미션이 null인 사원의 이름, 커미션을 출력하세요.
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
file[file.COMMISSION_PCT.isnull()][['LAST_NAME', 'COMMISSION_PCT']].fillna(0)
```

[문제140] 커미션이 null이 아닌 사원의 이름, 커미션을 출력하세요.
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
# notnull()
file[file.COMMISSION_PCT.notnull()][['LAST_NAME', 'COMMISSION_PCT']]

# ~ + isnull()
file[~file.COMMISSION_PCT.isnull()][['LAST_NAME', 'COMMISSION_PCT']]
```

[문제141] last_name 첫 글자가 S로 시작되는 사원들의 last_name을 출력하세요
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
file[file.LAST_NAME.apply(lambda x: x.startswith('S'))].LAST_NAME
```

[문제142] last_name이 g로 끝나는 사원들의 이름, 급여 출력하세요.
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
file[file.LAST_NAME.apply(lambda x: x.endswith('g'))][['LAST_NAME', 'SALARY']]
```

[문제143] 110번 사원의 급여보다 많이 받는 사원들의 이름, 급여를 출력하세요.
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
file[file.SALARY > int(file[file.EMPLOYEE_ID == 110].SALARY)][['LAST_NAME', 'SALARY']]
```

[문제144] 관리자 사원의 이름, 입사일, 급여를 출력하세요.
```python
import pandas as pd
import numpy as np
file = pd.read_csv('C:/Users/stu/git/DA_Academy/emp_new.csv')
file[file.EMPLOYEE_ID.isin(set(file.MANAGER_ID.dropna().apply(int)))][['LAST_NAME', 'HIRE_DATE','SALARY']]
```
```python
with open('C:/Users/stu/git/DA_Academy/emp_new.csv', 'r') as emp:
    mgr = []
    next(emp)
    for line in emp:
        m_id = line.split(',')[9]
        if len(m_id) > 0:
            mgr.append(m_id)
    mgr = list(set(mgr))
    
with open('C:/Users/stu/git/DA_Academy/emp_new.csv', 'r') as emp:    
    for line in emp:
        data = line.split(',')
        if data[0] in mgr:
            print('관리자 {}의 입사일은 {}, 급여는 {} 입니다.'.format(data[2], data[5], data[7]))
```

# 순위
- ## pandas
    - ### rank()
        -  `데이터.rank(ascending=오름차순여부, method=동일값처리방법, na_option=na값처리방법)`
        -  동일값처리방법
            -  average: 기본값, 순위의 평균으로 통일
            -  min: 가장 낮은 숫자로 통일 # SQL의 rank
            -  max: 가장 높은 숫자로 통일
            -  first: 인덱스가 작은 숫자부터
            -  dense: 중복된 순위를 건너뛰지 않음 # SQL의 dense_rank
            ```python
            obj.rank(ascending=False, method='dense')
            ```
            ```
            0    7.0
            1    4.0
            2    1.0
            3    6.0
            4    9.0
            5    2.0
            6    8.0
            7    5.0
            8    3.0
            9    3.0
            dtype: float64
            ```
        -  na값 처리방법
            -  keep: 순위 계산에서 NaN 제외
            -  top: NaN을 가장 높은 순위로 계산
            -  bottom: NaN을 가장 낮은 순위로 계산

# NaN/None
-  파이썬 자체 None 
    ```python
    obj = Series([1,2,3,None,5])
    ```

- ## numpy
    - ### nan
        -  NaN값
        -  `np.nan`
            ```python
            import numpy as np
            obj2 = Series([70, 60, 80, np.nan, 90])
            obj2.sort_values()
            ```
            ```
            1    60.0
            0    70.0
            2    80.0
            4    90.0
            3     NaN
            dtype: float64
            ```
    - ### fillna()
        -  객체의 na값을 지정한 값으로 채움
        -  `객체.fillna(값, inplace=데이터에 적용여부, method=방법)`
            ```python
            df.fillna({0:0, 1:1, 2:2, 4:4})  # 열 별로 다른 값을 채우고 싶을 때
            ```
            ```
                0	1	2	4
            0	1.0	2.0	3.0	4.0
            1	1.0	1.0	2.0	4.0
            2	0.0	1.0	2.0	4.0
            3	0.0	2.0	3.0	4.0
            ```
        -  방법: ffill, pad, bfill, backfill
            
    -  ### dropna()
        -  객체의 na값을 제외한 값을 리턴
        -  `객체.dropna(how=방법, axis=축)`
            -  any: 행에 NaN이 하나라도 있을 시 제외
            -  all: 해당 축의 모든 값이 NaN일때만 제외
                ```python
                from numpy import nan as NA
                df = DataFrame([[1,2,3], [1,None, NA], [NA, NA, NA], [NA,2,3]])
                df.dropna(how='all', axis=0) # 행의 모든 값이 NaN일때만 제외
                ```
                ```
                    0	1	2
                0	1.0	2.0	3.0
                1	1.0	NaN	NaN
                3	NaN	2.0	3.0
                ```
                ```python
                df.dropna(how='all', axis=1) # 열의 모든 값이 NaN일때만 제외
                ```
                ```
                    0	1	2
                0	1.0	2.0	3.0
                1	1.0	NaN	NaN
                2	NaN	NaN	NaN
                3	NaN	2.0	3.0
                ```
                
    -  ### sort_values()
        -  `객체.sort_values(ascending=오름차순여부, na_position=NaN위치)`
        -  위치: first(제일 앞), last(제일 뒤)

## pandas
-  ### isin()
    -  객체에 해당 값이 있는지 확인
    -  `객체.isin(값)`
        ```python
        df = DataFrame({'영어':[60,80,70], '수학':[50,72,86]}, index=['홍길동', '박찬호', '손흥민'])
        df[df['수학'].isin([72, 86])]
        ```
        ```
                영어	수학
        박찬호	80	72
        손흥민	70	86
        ```
        ---
        ```python
        df[~df['수학'].isin([72, 86])] # ~ : 포함하지 않는
        ```
        ```
            영어	수학
        홍길동	60	50
        ```

-  ### apply()
    -  행, 열 값을 인수로 받아서 지정한 함수를 적용
    -  `객체.apply(함수, axis=축)`
        ```python
        s1 = Series([1,2,3])
        s1.apply(lambda x: x**2)
        ```
        ```
        0    1
        1    4
        2    9
        dtype: int64
        ```
        ---
        ```python
        df.apply(np.sum, axis=0) # 행을 기준으로 열 더하기
        ```
        ```
        0    5
        1    7
        2    9
        ```
        ---
        ```python
        df.apply(np.sum, axis=1) # 열을 기준으로 행을 더하기
        ```
        ```
        0     6
        1    15
        dtype: int64
        ```